import type { AssetType, AlexaDeviceState, Routine, Scene } from '../types';

export interface AssetDefinition {
  type: AssetType;
  label: string;
  emoji: string;
  isAlexaDevice: boolean;
  color: string;
  defaultState: AlexaDeviceState;
  defaultDescription: string;
}

export const ASSET_DEFINITIONS: AssetDefinition[] = [
  // Alexa / IoT Devices
  {
    type: 'smart-bulb',
    label: 'Smart Bulb',
    emoji: '💡',
    isAlexaDevice: true,
    color: '#FFD700',
    defaultState: { isOn: true, brightness: 80, colorTemp: 3000, powerConsumption: 9 },
    defaultDescription: 'Alexa-controlled smart light bulb with adjustable brightness and color temperature.',
  },
  {
    type: 'echo-dot',
    label: 'Echo Dot',
    emoji: '🔊',
    isAlexaDevice: true,
    color: '#3a3a5e',
    defaultState: { isOn: true, volume: 50, powerConsumption: 3 },
    defaultDescription: 'Amazon Echo Dot (5th Gen) smart speaker with Alexa voice assistant.',
  },
  {
    type: 'echo-show',
    label: 'Echo Show',
    emoji: '📺',
    isAlexaDevice: true,
    color: '#1e2a4a',
    defaultState: { isOn: true, brightness: 70, volume: 40, powerConsumption: 20 },
    defaultDescription: 'Amazon Echo Show 10 with rotating screen for visual responses and video calls.',
  },
  {
    type: 'smart-plug',
    label: 'Smart Plug',
    emoji: '🔌',
    isAlexaDevice: true,
    color: '#4CAF50',
    defaultState: { isOn: false, powerConsumption: 0 },
    defaultDescription: 'Alexa-compatible smart plug for controlling any appliance remotely.',
  },
  {
    type: 'motion-sensor',
    label: 'Motion Sensor',
    emoji: '👁️',
    isAlexaDevice: true,
    color: '#FF9800',
    defaultState: { isOn: true, motionDetected: false, batteryLevel: 87, powerConsumption: 0.5 },
    defaultDescription: 'Passive infrared motion sensor for Alexa automations and security routines.',
  },
  {
    type: 'thermostat',
    label: 'Smart Thermostat',
    emoji: '🌡️',
    isAlexaDevice: true,
    color: '#2196F3',
    defaultState: { isOn: true, temperature: 22, humidity: 45, powerConsumption: 4 },
    defaultDescription: 'Smart thermostat controllable via Alexa for precise climate management.',
  },
  {
    type: 'smart-lock',
    label: 'Smart Lock',
    emoji: '🔒',
    isAlexaDevice: true,
    color: '#9C27B0',
    defaultState: { isOn: true, isLocked: true, batteryLevel: 72, powerConsumption: 0.8 },
    defaultDescription: 'Alexa-enabled smart lock for keyless entry and remote monitoring.',
  },
  {
    type: 'camera',
    label: 'Security Camera',
    emoji: '📷',
    isAlexaDevice: true,
    color: '#607D8B',
    defaultState: { isOn: true, motionDetected: false, powerConsumption: 5 },
    defaultDescription: 'Indoor security camera viewable through Alexa Show devices and the app.',
  },
  {
    type: 'smoke-detector',
    label: 'Smoke Detector',
    emoji: '🚨',
    isAlexaDevice: true,
    color: '#F44336',
    defaultState: { isOn: true, batteryLevel: 95, powerConsumption: 0.5 },
    defaultDescription: 'Smart smoke detector with Alexa integration for instant alerts.',
  },
  {
    type: 'smart-tv',
    label: 'Smart TV',
    emoji: '📺',
    isAlexaDevice: true,
    color: '#212121',
    defaultState: { isOn: false, volume: 30, brightness: 80, channel: 5, powerConsumption: 120 },
    defaultDescription: 'Alexa-compatible smart TV for voice-controlled entertainment.',
  },
  {
    type: 'ceiling-fan',
    label: 'Ceiling Fan',
    emoji: '🌀',
    isAlexaDevice: true,
    color: '#90A4AE',
    defaultState: { isOn: false, speed: 2, powerConsumption: 60 },
    defaultDescription: 'Smart ceiling fan with Alexa speed control and scheduling.',
  },
  {
    type: 'doorbell',
    label: 'Video Doorbell',
    emoji: '🔔',
    isAlexaDevice: true,
    color: '#FF8F00',
    defaultState: { isOn: true, motionDetected: false, batteryLevel: 88, powerConsumption: 2 },
    defaultDescription: 'Ring-compatible video doorbell with Alexa announcements.',
  },
  {
    type: 'air-purifier',
    label: 'Air Purifier',
    emoji: '💨',
    isAlexaDevice: true,
    color: '#4DD0E1',
    defaultState: { isOn: false, speed: 1, airQuality: 35, powerConsumption: 40 },
    defaultDescription: 'Smart air purifier with AQI monitoring and Alexa voice control.',
  },
  // Furniture
  {
    type: 'sofa',
    label: 'Sofa',
    emoji: '🛋️',
    isAlexaDevice: false,
    color: '#795548',
    defaultState: { isOn: false },
    defaultDescription: 'Living room sofa.',
  },
  {
    type: 'bed',
    label: 'Bed',
    emoji: '🛏️',
    isAlexaDevice: false,
    color: '#ECEFF1',
    defaultState: { isOn: false },
    defaultDescription: 'Bedroom bed.',
  },
  {
    type: 'table',
    label: 'Table',
    emoji: '🪵',
    isAlexaDevice: false,
    color: '#A1887F',
    defaultState: { isOn: false },
    defaultDescription: 'Dining or coffee table.',
  },
  {
    type: 'chair',
    label: 'Chair',
    emoji: '🪑',
    isAlexaDevice: false,
    color: '#8D6E63',
    defaultState: { isOn: false },
    defaultDescription: 'Chair.',
  },
  {
    type: 'tv-stand',
    label: 'TV Stand',
    emoji: '🖥️',
    isAlexaDevice: false,
    color: '#546E7A',
    defaultState: { isOn: false },
    defaultDescription: 'Television stand unit.',
  },
  {
    type: 'bookshelf',
    label: 'Bookshelf',
    emoji: '📚',
    isAlexaDevice: false,
    color: '#6D4C41',
    defaultState: { isOn: false },
    defaultDescription: 'Bookshelf for storage.',
  },
  {
    type: 'bathtub',
    label: 'Bathtub',
    emoji: '🛁',
    isAlexaDevice: false,
    color: '#E0F7FA',
    defaultState: { isOn: false },
    defaultDescription: 'Bathroom bathtub.',
  },
  {
    type: 'desk',
    label: 'Desk',
    emoji: '🖥️',
    isAlexaDevice: false,
    color: '#BCAAA4',
    defaultState: { isOn: false },
    defaultDescription: 'Work or study desk.',
  },
  {
    type: 'plant',
    label: 'Plant',
    emoji: '🪴',
    isAlexaDevice: false,
    color: '#388E3C',
    defaultState: { isOn: false },
    defaultDescription: 'Decorative indoor plant.',
  },
  {
    type: 'wardrobe',
    label: 'Wardrobe',
    emoji: '🚪',
    isAlexaDevice: false,
    color: '#8D6E63',
    defaultState: { isOn: false },
    defaultDescription: 'Bedroom wardrobe for clothing storage.',
  },
];

export const ASSET_MAP = new Map<AssetType, AssetDefinition>(
  ASSET_DEFINITIONS.map((a) => [a.type, a])
);

// Room positions match the node graph in src/constants/layout.ts.
// House is centered on world origin; total extent: x[-12,12] z[-8,8].
export const DEFAULT_ROOMS = [
  {
    id: 'living-room',
    name: 'Living Room',
    icon: '🛋️',
    width: 16,
    depth: 8,
    height: 3,
    position: { x: -4, y: 0, z: -4 },
    color: '#E8C88A',
    floorColor: '#C8894A',
    wallColor: '#F0DDB0',
  },
  {
    id: 'kitchen',
    name: 'Kitchen',
    icon: '🍳',
    width: 8,
    depth: 8,
    height: 3,
    position: { x: 8, y: 0, z: -4 },
    color: '#8CC8D8',
    floorColor: '#5AAAC0',
    wallColor: '#C0E8F4',
  },
  {
    id: 'master-bedroom',
    name: 'Master Bedroom',
    icon: '🛏️',
    width: 8,
    depth: 8,
    height: 3,
    position: { x: -8, y: 0, z: 4 },
    color: '#C898DC',
    floorColor: '#A060C0',
    wallColor: '#E8D0F8',
  },
  {
    id: 'bathroom',
    name: 'Bathroom',
    icon: '🚿',
    width: 4,
    depth: 8,
    height: 3,
    position: { x: -2, y: 0, z: 4 },
    color: '#80D8B0',
    floorColor: '#48B888',
    wallColor: '#C0F0E0',
  },
  {
    id: 'office',
    name: 'Home Office',
    icon: '💼',
    width: 8,
    depth: 8,
    height: 3,
    position: { x: 8, y: 0, z: 4 },
    color: '#D0D060',
    floorColor: '#A8A830',
    wallColor: '#ECEC90',
  },
];

export const DEFAULT_ROUTINES: Routine[] = [
  {
    id: 'good-morning',
    name: 'Good Morning',
    emoji: '🌅',
    triggerLabel: 'Every day at 7:00 AM',
    isEnabled: true,
    lastRun: Date.now() - 3600000 * 8,
  },
  {
    id: 'movie-time',
    name: 'Movie Time',
    emoji: '🎬',
    triggerLabel: 'Voice command: "Alexa, movie time"',
    isEnabled: true,
  },
  {
    id: 'good-night',
    name: 'Good Night',
    emoji: '🌙',
    triggerLabel: 'Every day at 10:30 PM',
    isEnabled: true,
    lastRun: Date.now() - 3600000 * 12,
  },
  {
    id: 'away-mode',
    name: 'Away Mode',
    emoji: '🏠',
    triggerLabel: 'When you leave home',
    isEnabled: false,
  },
  {
    id: 'evening-relax',
    name: 'Evening Relax',
    emoji: '🕯️',
    triggerLabel: 'Every day at 6:00 PM',
    isEnabled: true,
  },
];

export const DEFAULT_SCENES: Scene[] = [
  {
    id: 'morning',
    name: 'Good Morning',
    emoji: '🌅',
    description: 'Bright lights, 22°C',
    color: '#FF8C00',
  },
  {
    id: 'movie',
    name: 'Movie Night',
    emoji: '🎬',
    description: 'Dim lights, TV on',
    color: '#6A0DAD',
  },
  {
    id: 'night',
    name: 'Good Night',
    emoji: '🌙',
    description: 'Lights off, lock doors',
    color: '#1a237e',
  },
  {
    id: 'away',
    name: 'Away Mode',
    emoji: '✈️',
    description: 'All off, camera on',
    color: '#1B5E20',
  },
];
